spring.application.name=autenticacion
server.servlet.context-path=/auth-service

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/autenticacion
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=7s3r
spring.datasource.password=p455

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Configuration
jwt.secret=miClaveSecretaSuperSeguraParaJWT12345678901234567890
jwt.expiration=86400000
